### ISSUE TITLE
Create Release Notes for 4.1

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride-docs#79]
https://hackmd.io/McqTXGtyQuSu1-QJz34xKw?both
-Eideren

**Comment by VaclavElias** [comment]
Can we pin this issue on the top temporarily?

**Comment by Eideren** [comment]
A bit awkward to do it this way but that's alright.
Included a couple more from PRs. I don't remember if xen merged something directly to main that's not part of the build changes/Net6 ?

**Comment by VaclavElias** [comment]
You mean that we should write these directly to the documentation? I just didn't know what is the workflow for docs before the new "major" release. I assume more of us could contribute to the release notes but if it is pushed to the master then you can't publish the master because there are new updates?

This issue is rather just a reminder or a summary. Let me know what is better :)

**Comment by xen2** [comment]
In the past, hackmd.io was quite helpful to write this kind of document in real-time and collaboratively.
However, it worked because only a few people worked on it and we could keep the link private (no permission issues nor account needed).

Some other ideas:
- GitHub wiki page
- directly where it should be on stride-docs repo in `ReleaseNotes.md`
- Check hackmd, if we can properly set permissions using github account, that might be the best option?

but conflicts might happen much more easily than when using a proper real-time collaborative editing platform.

**Comment by Eideren** [comment]
We could just setup an hackmd file with permissions, maximum of 4 account with edit rights but anyone is free to comment.
I already setup editing permissions for @xen2, @Aggror and @VaclavElias. @xen2 you have two different account on that platform, tell me if the one I added was the right one.
https://hackmd.io/McqTXGtyQuSu1-QJz34xKw#

**Comment by VaclavElias** [comment]
Thanks, this is the way! I can access it.

**Comment by VaclavElias** [comment]
Tracked here https://github.com/stride3d/stride/issues/1409 and here https://github.com/stride3d/stride/issues/1386
